FROM httpd:2.4.43

RUN apt-get update && \
    apt-get -y install curl

HEALTHCHECK --interval=2s --timeout=2s --retries=3 \
  CMD curl --silent --fail localhost || exit 1

COPY test/httpd.conf /usr/local/apache2/conf/httpd.conf

# MyFav installation
COPY html/ /usr/local/apache2/cgi-bin/MyFavoriteThings/html/
COPY lib/MyFav /usr/local/apache2/cgi-bin/MyFavoriteThings/lib/MyFav/
COPY myfavCss/ /usr/local/apache2/cgi-bin/MyFavoriteThings/myfavCss/
COPY cgi/ /usr/local/apache2/cgi-bin/MyFavoriteThings/cgi

# copy our custom made perl distribution
COPY --from=myfav_perl_distribution:latest /tmp/myfav_perl_distribution/ /usr/local/apache2/cgi-bin/MyFavoriteThings/perl5/

RUN chmod u+x /usr/local/apache2/cgi-bin/MyFavoriteThings/cgi/*

RUN chown daemon /usr/local/apache2/htdocs
RUN chown -R daemon /usr/local/apache2/cgi-bin/

RUN mkdir /usr/local/apache2/cgi-bin/MyFavoriteThings/data
RUN chown daemon /usr/local/apache2/cgi-bin/MyFavoriteThings/data